@API_HostAddress = http://localhost:5285

POST {{API_HostAddress}}/api/account
Content-Type: application/json
Accept: application/json

{
    "name": "tester_123!",
    "email": "tester@mail.com",
    "password": "some_Secret!123"
}

###
